### ISSUE TITLE
Possible unwanted function redefined in api/tasks.py

### ISSUE THREAD

**Issue by zx9r** [Reckless-Satoshi/robosats#114]
Function users_cleansing is defined twice in file api/tasks.py

Since it is decorated with shared_task decorator I guess it is hiding any problem as the function is not directly called but I'm not sure if any problem can arise derived from this.

It seems a copy/paste error. Probably would better to name second definition (line 43) as give_rewards()

**Comment by Reckless-Satoshi** [comment]
Indeed, this seems to be a mistake (copy/pasting related). Line 43 function should be renamed as give_rewards(). 

Weird enough, it went undetected since the task works as expected and the compiler doesn't raise any error :)

**Comment by Reckless-Satoshi** [comment]
Fixed in the latest patch.
