### ISSUE TITLE
Add Ukrainian Hryvnia

### ISSUE THREAD

**Issue by rkfg** [Reckless-Satoshi/robosats#124]
It's currently missing from the list of fiat currencies and I guess it might be useful given the current situation!

**Comment by Reckless-Satoshi** [comment]
Hey @rkfg, the currency is available in at least one of the external price providers. So you can expect to see it added in the next platform update!

**Comment by Reckless-Satoshi** [comment]
New currency added https://github.com/Reckless-Satoshi/robosats/commit/26155fe4518063c271c7bcf51ff9525f60ffa2f9
Will be up on mainnet sometime before the week ends.
