### ISSUE TITLE
Detailed amounts of sats involved after a trade 

### ISSUE THREAD

**Issue by ibertario** [Reckless-Satoshi/robosats#150]
At the end of the trade (therefore also in the information that is seen when entering in the order later) add the summary of the exact amount of Deposit, Commission and sats bought / sold:

Concept from @dehiv that includes data from maker and taker:
![image](https://user-images.githubusercontent.com/68381662/170606053-72e81a3d-e1ad-4e2b-acd6-94af5ca97e5c.png)

I propose refer only to the part of the Robot that is viewing the order, so:

MAKER screen:
![maker](https://user-images.githubusercontent.com/68381662/170616740-ff2b735b-5016-44a1-9cd2-813b4a47954b.jpg)

TAKER screen:
![taker](https://user-images.githubusercontent.com/68381662/170616726-a07d8a1f-39df-41bc-8cf4-b565aa50f4f7.jpg)

_* You can add the fees payed by RoboSats_ and some other info if needed there

**Comment by Reckless-Satoshi** [comment]
Implemented in commit https://github.com/Reckless-Satoshi/robosats/commit/834733cb616a28e09597d3b386a35ed6a93f2ee8 ! Closing this issue
