### ISSUE TITLE
Same backup code, shows new robot avatar, name and referral link

### ISSUE THREAD

**Issue by openoms** [Reckless-Satoshi/robosats#159]
**Describe the bug**
Saved a backup code and share the referral link - so came back to check it.
The robot name, avatar and referral link is now changed after ~2 weeks.

**To Reproduce**
Restore the same backup code 2 weeks later,

**Expected behavior**
Same account should come up as tested previously.

**Screenshots**
If applicable, add screenshots to help explain your problem. Be aware to not reveal any personal data.

**Desktop (please complete the following information):**
 - OS: [Debian11]
 - Browser [Tor]
 - Version [11.0.13 ]

**Smartphone (please complete the following information):**
 - Same on the CalyxOS phone with Tor Browser

**Additional context**
Should be recorded in the readme if the avatar is expected to change periodically or after backend updates.

**Comment by Reckless-Satoshi** [comment]
Hey @openoms, 

With the introduction of the new message encryption scheme we had to upgrade how robots are generated. We ran a "transition fork" for 4-5 days from tokens V1 to tokens V2.

Any V1 token robot cannot be used in the frontend. These also cannot participate in orders anymore (they do not have a pair of PGP keys, so they cannot communicate). You shouldn't reuse your robot avatar in any case.

You can still log in with the V1 token into the same robot making a call directly through the API web interface:
`

**Comment by openoms** [comment]
Thank you for the explanation!
This is not a burning problem and only for documentation, but if I try 
`http://robosats6tkf3eva7x2voqso3a5wcorsnw34jveyxfqi2fu7oyheasid.onion/user/?token=ANY_ROBOT_TOKEN`
I just get:
```
Not Found
The requested resource was not found on this server.
```

**Comment by Reckless-Satoshi** [comment]
> Thank you for the explanation! This is not a burning problem and only for documentation

My bad! Wrote the endpoint wrongly. Missing the /api/ .

> http://robosats6tkf3eva7x2voqso3a5wcorsnw34jveyxfqi2fu7oyheasid.onion/api/user/?token=ANY_ROBOT_TOKEN

**Comment by openoms** [comment]
Great, can access the old avatar just in case. 

If the generation of the robots is not expected to change for now (or without notice) this can be closed.
