### ISSUE TITLE
“Extra” features to increase the popularity of RoboSats

### ISSUE THREAD

**Issue by LindomarRodrigues** [Reckless-Satoshi/robosats#179]
**Is your feature request related to a problem? Please describe.**
RoboSats is not known and accessed by many people, so often the order book for some currencies ends up being empty for a long time, a fact that is very frustrating and makes it impossible to use the platform.

**Describe the solution you'd like**

- Landing page more “commercial” and less a presentation of the open source project, aiming to acquire new users of the system and not new contributors (which will obviously happen naturally if the system is useful to them), in addition to having versions in other languages.

- Allow trading on side chain (for now only Liquid seems decent to me), a system similar to the one implemented in [coinos](https://github.com/coinos) can be used, but I would have to look at the licensing issues.

- A sports betting system (other types of bets can also be implemented in a second moment) totally P2P and using the lightning network, with the odds being dynamically generated, aiming to balance the amounts of sats in each possibility of result would probably win over some users, who could maybe use p2p to buy more sats (or sell).

- The idea of ​​WebView is acceptable, but a native mobile application would definitely draw more attention and give more credibility to the project, in addition to being a differentiator compared to other p2p exchanges.

**Additional context**
I already tried to create an mobile application that connects via Tor a few years ago and my experience was not the best, so maybe this is unfeasible with few programmers contributing, a lot will have to be done from scratch.

The betting idea I already have a draft implemented, so I could actively contribute a lot to the development of this feature.

Other casino games can also be added, but there are already so many that I don't know if it would really attract new users.

**Comment by LindomarRodrigues** [comment]
I'm willing to contribute to the development of some of these or even other features (as long as it aims to attract new users), so if anyone has an idea and doesn't want to create a new issue, they could add it here below I think.

**Comment by Reckless-Satoshi** [comment]
Hey @LindomarRodrigues, thank you very much for all of these suggestions!
>     * Landing page more “commercial” and less a presentation of the open source project
Are you referring to the landing page of the app (robosats.com)? or the documentation site (learn.robosats.com)?

>     * Allow trading on side chain (for now only Liquid seems decent to me)

Worth researching! :D

>     * The idea of ​​WebView is acceptable, but a native mobile application would definitely draw more attention and give more credibility to the project, in addition to being a differentiator compared to other p2p exchanges.

Agree! but we do not have the developer power at the moment... The webview app is a low hanging fruit. In addition, I would bet 99% of the users cannot tell the difference between React Native and ReactJS in Webview :D . The current prototype of Webview app work amazingly well (I myself would not be able to tell it's a Webview...)

> **Additional context** I already tried to create an mobile application that connects via Tor a few years ago and my experience was not the best, so maybe this is unfeasible with few programmers contributing, a lot will have to be done from scratch.

Can you be more explicit on what exactly will be not feasible?

---------
In other order of things, and this is **just my opinion** down here:

Attracting more users is about quality and outreach. Adding more features, per se, will not attract more users. 

RoboSats is a freedom tool, not entertainment. Therefore, it is unlikely to be turned into a casino. If we wanted to do so, we just need to implement shitcoins ;) Yet, I fully agree it will get more attention if it had shitcoins / betting / casino games: but more attention for the wrong reasons is worse than little attention.

Let's focus on what matters most and deliver a tool as great as possible, users will come in time :D

**Comment by LindomarRodrigues** [comment]
> Are you referring to the landing page of the app (robosats.com)? or the documentation site (learn.robosats.com)?

I refer to learn.robosats.com, in my opinion is to be a page friendly for new users and prepared for SEO, the ideal would be for “robosats” to appear if you search for “buy bitcoin p2p”, “buy lightning bitcoin” or “bitcoin without kyc”. Something that would facilitate this would be blog posts on these topics (it could even separate the blog into another repository in some simple way for anyone to contribute articles without much friction).

**Comment by Reckless-Satoshi** [comment]
> buy bitcoin p2p”, “buy lightning bitcoin” or “bitcoin without kyc”

This would be  great. learn.robosats.com is a markdown site that anyone can edit and open a PR. 

Each single page can also be added the frontmatter key `excerpt`. According to the Minimal Mistakes Jekyll template:
```
excerpt: "A unique line of text to describe this post that will display in an archive listing and meta description with SEO benefits."
```

The documentation site is still a work in progress and is missing a lot of text. It would be very useful if anyone with SEO knowledge can take a look at it.

**Comment by LindomarRodrigues** [comment]
> It would be very useful if anyone with SEO knowledge can take a look at it.

I have some knowledge of SEO, but my English sucks, so I can't contribute much to it right now.

But something simple that can be done is to ask to be added backlinks to the sites that launch articles presenting the platform, Google favors a lot of sites linked by others in the same niche.

I saw that there's an author from Bitcoin Magazine preparing something about RoboSats, a backlink with the Do-Follow tag would definitely help a lot.

**Comment by Reckless-Satoshi** [comment]
Closing as this issue was very general and got stagnant. Better to open a new issue with concrete ideas or requests for features.
