### ISSUE TITLE
Add the fiat amount to the chat component

### ISSUE THREAD

**Issue by alaznem** [Reckless-Satoshi/robosats#192]
Related to the UX issue for small screens #181, but also as a general UX improvement we could improve the visibility of the taken trade amount in the chat component. This is especially relevant for taken amount range orders where the maker is using a small screen device.

Furthermore if stealth invoices #168 are rolled out and enabled by the makers, the demand for this feature might surge. Since the taken amount does not show up to the maker in the trade escrow lightning invoice anymore, switching to the order tab would be mandatory to check if the correct amount has been sent by the taker if this feature is not implemented until then.

# Solution I'd like

**General**: Add the fiat amount everywhere where {{currencyCode}} (this.props.data.currencyCode) is being used.

**Explicit occurrences** I stumbled upon (probably not a concluding list):

- [x] Add fiat amount to the maker confirm button for all locales https://github.com/Reckless-Satoshi/robosats/blob/98e2da68d0b690aaab0036562c01b90db87dbc9c/frontend/static/locales/en.json#L370
- [x] Add fiat amount to the taker confirm button for all locales https://github.com/Reckless-Satoshi/robosats/blob/98e2da68d0b690aaab0036562c01b90db87dbc9c/frontend/static/locales/en.json#L369
- [x] Add fiat amount to the dialog title: `Confirm you received {{tradeAmount}} {{currencyCode}}?` https://github.com/Reckless-Satoshi/robosats/blob/98e2da68d0b690aaab0036562c01b90db87dbc9c/frontend/src/components/TradeBox.js#L175
- [x] Add fiat amount to the dialog content https://github.com/Reckless-Satoshi/robosats/blob/98e2da68d0b690aaab0036562c01b90db87dbc9c/frontend/src/components/TradeBox.js#L179
- [x] Add fiat amount to the chat introduction text https://github.com/Reckless-Satoshi/robosats/blob/98e2da68d0b690aaab0036562c01b90db87dbc9c/frontend/static/locales/en.json#L375

# How to get this feature implemented

@Reckless-Satoshi this feature looks like it has a low complexity to implement, if the trade amount is available as a variable already.

There is some work to be done to identify all the occurrences and then the strings could be updated easily. If your strategy of the developer rewards panel fits to bounty low complexity tasks, I would love to donate 50k sat for this feature.

**Comment by Reckless-Satoshi** [comment]
Easy fix. I will commit these changes when I get a bit of time.

**Comment by Reckless-Satoshi** [comment]
Implemented in https://github.com/Reckless-Satoshi/robosats/commit/1b8f91457cc370d777805b2f7c0b85f6c02bac03 . Up in testnet. Took a bit longer than expected: we have quite some translations files to maintain already!

**Comment by alaznem** [comment]
> @alaznem Implemented in [1b8f914](https://github.com/Reckless-Satoshi/robosats/commit/1b8f91457cc370d777805b2f7c0b85f6c02bac03) . Up in testnet. Took a bit longer than expected: we have quite some translations files to maintain already!

WOW thanks, looks nice and seamless in action! :+1: :tada:

**Comment by Reckless-Satoshi** [comment]
> I would like to fund your development of this feature with 50k sats. Invoice needed. ;-)

Amazing! Thank you very much. I will directly re-donate your donation to RoboSats node so it can be used on future features :)

lnbc500u1p3w88dcpp5007p5vp0xe02zjvp0wmmwkt2sfc5w732y5xv0y49p2n8h6yk3akqdzsf9ehxat9yq3nzwfjypjx7mnpw35k7m3qwfjkg6tjv43hgetyyp6x7gr8v4hx2unpdssygetkypr82mnycqzpgxqyd9uqsp5eefyvqps8faal6vduheckwgxsu3a5rvcxs7gqz5spggtcgjedryq9qyyssqgxamm9vru6ahf4qh5hnujrqq3gfsf7j4tr9t4x2zysyjcu9hh2wneezp46asp0rjqx4vkk7fk2n2c8u3a4kwwp77m6v640j4c9ay3kqpdj42g5
