### ISSUE TITLE
Name and ava not refreshing after generating new robo token

### ISSUE THREAD

**Issue by kimoraku** [Reckless-Satoshi/robosats#238]
**Describe the bug**
Name and ava not refreshing after generating new robo token

**To Reproduce**
on the robot token page:
1- your first name appears + random token number associated with it (example: SecuredPot6  / Q6luTVmChTUvIJ0k8ZLAUha8vuWpBMTG9ZFt )
2- you don't like the name, and the user hits the dice-icon to re-generate a token
3- A new token number is presented BUT the name and avator aren't updated yet (example: SqZhhkTz2h8QPEu4M08ON98XSNsHeRNVoM3t -
4- when a user copy-pastes the second token number, and didn't pay attention to the earlier name, they can think this is still for "SecuredPot6" , while in fact it's not.
5- the new second token doens't trigger a refresh of the name+ava
6- this can cause confusion for users who write down their token + name often

**Expected behavior**
After generating a new token, a user expects the avatar and name to update automatically to the one associated with the newly generated token.

context:
 this can cause confusion for users who write down their token + name often

**Comment by Reckless-Satoshi** [comment]
Indeed, while the first robot is generated without user input at all once the app loads, any subsequent robot avatar generation is comprised of 2 step:
- Step 1. Enter your new token: it can be some keyboard input; a past token (recovery); or, a randomly generated token by your browser (click the Dice button). 
- Step 2. Submit the new token for robot generation (Click "Generate Robot" button)

As pointed, this is unintuitive for new users. The Clipboard button, usually in blue, becomes grey when the token has been modified but no new robot was generated, however this might go unnoticed. 

I am unsure whether we are going to find a short term solution or center our efforts on Issue https://github.com/Reckless-Satoshi/robosats/issues/204 and make a more profound remodel of the robot generation flow.

**Comment by Reckless-Satoshi** [comment]
Closing since this issue will be worked on in the new landing page.
