### ISSUE TITLE
UX suggestion - changing title bar as additional event notification (in addition to ring)

### ISSUE THREAD

**Issue by kristapsk** [Reckless-Satoshi/robosats#283]
When other party takes your order, there is a bell (audio) notification. But in Tor Browser by default NoScript disables media playback, so user will not notice that, unless manually confirming specific media file. Instead there is just this following error popup:
![image](https://user-images.githubusercontent.com/4500994/195679988-7d61da20-26ef-4840-994f-41502a408fcd.png)

Would be cool to have some blinking / changing title as additional notificaiton option, so that user could have his Tor Browser minimized in the title bar and see notification there. You could also just be having sound on your computer muted for some reason as well. Something like https://stackoverflow.com/a/7617318/2704037.

**Comment by Reckless-Satoshi** [comment]
Changing the page title is a very clever way to bring the user attention. I think using some bright/colorful emojis for each state and making them blink will do the job very well. In addition to that, bringing push notifications to the native Android app is the best way to go.

And indeed, NoScript blocks sound notifications https://github.com/Reckless-Satoshi/robosats/issues/41 . Experiene so far is that a newly installed Tor Browser that has not been customize will not block RoboSats sounds (tested in Windows & Linux).

**Comment by kristapsk** [comment]
> Experiene so far is that a newly installed Tor Browser that has not been customize will not block RoboSats sounds (tested in Windows & Linux).

For me it's blocked by default (on Gentoo Linux, but not installed from OS packages).

**Comment by Reckless-Satoshi** [comment]
The new Notification component will make the tab blink with a custom message for every notification type. The blinking page title will only fire if the user is in another tab (it will not fire if the tab is on focus and the user is in another application). On user return to page, the blinking will stop. There are new notifications for "User has rewards" and "There is a new message in the chat". All notifications fire regardless of where the user is in the app, as long as the user has an active order.

The sounds are now fired from a hidden div, so in case of conflict with NoScript it should not cause any UI issue (untested).
