### ISSUE TITLE
Show small hints and description on mouse hover

### ISSUE THREAD

**Issue by Reckless-Satoshi** [Reckless-Satoshi/robosats#31]
For example hovering "Premium" gives you a small explanation of what it means. Useful for all the items in the form of the MakerPage.
In addition, there could be a on-by-default hint box over the Token TextField that reminds users to back it up.

**Comment by Reckless-Satoshi** [comment]
Mostly implemented in the latest PRs. Some more tips could still be added in the Order and Contract boxes.

**Comment by dbolser** [comment]
Please list the items where tips are missing

**Comment by Reckless-Satoshi** [comment]
> Please list the items where tips are missing

Most critical ToolTips are already in place. As of now it is a matter of double checking all over the whole app and see where some tooltips could still be useful if added. One could think of adding ToolTips in:
1 - Rows of the OrderPage (Order box). (E.g, tapping on `Premium` explains what premium is)
2 - Different steps of the TradeBox (Contract box). (E.g, tapping on `copy to clipboard` says 'copied!')
