### ISSUE TITLE
Can't take order

### ISSUE THREAD

**Issue by donverduras** [Reckless-Satoshi/robosats#335]
After I click take order the spinner gets stuck and I can't proceed with my order

**Comment by donverduras** [comment]
<img width="350" alt="Screenshot 2022-12-14 at 16 55 22" src="https://user-images.githubusercontent.com/2570015/207732952-1606cd69-11e8-47e5-aab7-8d3d44d3fdf4.png">

**Comment by redphix** [comment]
Have you tried asking in the Telegram group? Quite possibly this seems like a one-off issue because of some recent outages or updates. Not entirely sure, but @Reckless-Satoshi might be able to give a better answer.

**Comment by Reckless-Satoshi** [comment]
> <img alt="Screenshot 2022-12-14 at 16 55 22" width="350" src="https://user-images.githubusercontent.com/2570015/207732952-1606cd69-11e8-47e5-aab7-8d3d44d3fdf4.png">

Related to the few hours the coordinator's LND node was frozen a week ago. Can be safely closed.
