### ISSUE TITLE
Multilanguage Support

### ISSUE THREAD

**Issue by Reckless-Satoshi** [Reckless-Satoshi/robosats#35]
Make RoboSats available in more than just English.

**Comment by dbolser** [comment]
Does the code currently support i18n? e.g. is this just an issue of finding translations? Or does the i18n work need to be done on the code?

**Comment by Reckless-Satoshi** [comment]
> Or does the i18n work need to be done on the code?

This has to be done first.

In addition. There are a few places where English sentences are composed via scripts that will be difficult to make work on other languages.

The UI and texts are still very fluid. Let's wait at least until v0.2.0 release before putting the work into internationalization.

**Comment by Reckless-Satoshi** [comment]
Work in progress.
