### ISSUE TITLE
Hint for Amount when doing Bitcoin on-chain Swap In/Out mentions fiat, not bitcoin 

### ISSUE THREAD

**Issue by cointastical** [Reckless-Satoshi/robosats#351]
After choosing BTC for the currency, when I hover over the Amount field, the hint/tooltip message shows:

Actual behavior: 
"Amount of fiat to exchange for bitcoin"

But this is a Swap In/Out, not a fiat Buy/Sell.  There's no fiat involved.

Expect behavior:
"Amount of bitcoin to Swap"  
(or whatever wording works best.  Maybe it would know if it is a Swap In or a Swap Out and that message would reflect that ... e.g., "Amount of bitcoin to Swap In" for a LN -> on-chain BTC trade (?), and "Amount to Swap Out" for an on-chain BTC -> LN trade (?).)

**Comment by Reckless-Satoshi** [comment]
Good catch!
Commit https://github.com/Reckless-Satoshi/robosats/commit/e7f745be13c4e7be02e9cf2186c61ee2488aaa83 fixes this tooltip, now it is `Amount of BTC to swap for LN Sats`, as well as, the tooltip for the payment methods (had the same issue, mentioned fiat).
