### ISSUE TITLE
Make the frontend pretty.

### ISSUE THREAD

**Issue by Reckless-Satoshi** [Reckless-Satoshi/robosats#37]
The frontend is currently vanilla Material UI V5 with no theme whatsoever.

It is composed only by a few elements and users can only see 4 pages: home/user-generator, order maker, order book, order/contract box. It is in addition, the first time a write a frontend, so there is a lot that could be improved about style!

I know for a fact there is quite some artists out there :D Bring it on! Propose any idea you have and let's work on it together. Let's make RoboSats pretty!

**Comment by dbolser** [comment]
I like it currently. Please can you make this ticket 'SMART' by providing a clear definition of what a pretty interface looks like?

**Comment by Reckless-Satoshi** [comment]
Hey @dbolser , it is hard to make it SMART because I do not know what I am asking for :dagger: 

Summary of this ticket is "I have no idea what I am doing UI style-wise. But probably you do. Advice and help would be cool"  Of course, this ticket was opened long time ago, and UI has improved a great bit. So I will simply close it and apply more SMARTness going forward.
