### ISSUE TITLE
A tutorial explicitly made for OpenKeychain+RoboSats (/docs/)

### ISSUE THREAD

**Issue by Reckless-Satoshi** [Reckless-Satoshi/robosats#60]
As raised in the community groups, users should not trust the chat is not logged or encrypted (in fact, it is not in v0.1.0). It is best to PGP encrypt the sensitive information.

It would be ideal to create a straightforward and concise tutorial on how to use OpenKeychain with RoboSats. Would be great if it includes a complete use case: pubkey generation, key exchange in robosats' chat, and encryption decryption of the sensitive info.

Looking for volunteers for this one :D

**Comment by GianfrancoBazzani** [comment]
I'm going to create  the guide file in [docs](https://github.com/Reckless-Satoshi/robosats/tree/main/docs) folder. The format of the guide will be Markdown.
