### ISSUE TITLE
For @RoboSatsBot, Brave blocks Telegram links

### ISSUE THREAD

**Issue by cointastical** [Reckless-Satoshi/robosats#66]
After paying the commitment transaction to PUBLISH, I was given the option to ENABLE TELEGRAM NOTIFICATIONS

Clicking that, I see:

    Enable TG Notifications
    You will be taken to a conversation with RoboSats telegram bot. Simply open the chat and press "Start". Note that by enabling telegram notifications you might lower your level of anonimity.

I clicked Enable.

Expected result:
A new browser tab would be launched, and that would resolve by the next step:
My Telegram desktop client would open and the @RoboSatsBot would be summoned

Actual result:
A new browser tab launched, but after a short duration the page shows:

### “tg” links are blocked
This page has been blocked by Brave
ERR_BLOCKED_BY_CLIENT

The URL that the browser tab had was:
tg://resolve?domain=RoboSatsBot&start=[identifier]

I was able to manually summon the robot by DM and copy & pasting the
"start=[identifier]"

**Comment by cointastical** [comment]
This is on Brave Browser:
[Version 1.36.109 Chromium: 99.0.4844.51 (Official Build) (64-bit)]

To resolve, changing the message: 
 Simply open the chat and press "Start". 
to also describe how to manually enable Telegram notifications is to 
DM @RoboSatsBot, press the /Start and then paste "start=[identifier]"
(or whatever the correct procedure is to manually set this up.)

**Comment by Reckless-Satoshi** [comment]
Hey @cointastical ,

Indeed, there is quite a few functionalities that do not seem to work in Brave with TOR. Opening apps (such as telegram) or copying to clipboard seems to be artificially disabled. 

I believe these are security features of Brave when Private mode with TOR is enabled (in the local development environment, when Brave without TOR can be used, both Telegram and copying to clipboard works).

The work around to make the telegram bot work by using `/start [identifier]` works. But it is a bit convoluted to be included in the app. Another way would be to simply copy/paste the link to another browser (or Brave without Tor), also too convoluted for a "user friendly app". 

As of now, using Tor Browser is strongly recommended. In addition, we now have a good documentation of how to solve this problem so we can redirect users thanks to the Issue you opened :D
