### ISSUE TITLE
Give a 'Step x of y' infographic while trading

### ISSUE THREAD

**Issue by dbolser** [Reckless-Satoshi/robosats#69]
**Is your feature request related to a problem? Please describe.**
I didn't visually notice the difference between the bond and the trade invoices.

**Describe the solution you'd like**
Make it clearer that the bond has been paid and the trade now needs to be paid.
e.g. a 'milestone' type progress bar that shits along like the 'Order details' text does.

**Describe alternatives you've considered**
The order details text could grey out past steps instead of deleting them.

**Additional context**
I'm number blind.

**Comment by Reckless-Satoshi** [comment]
> **Describe the solution you'd like**
> Make it clearer that the bond has been paid and the trade now needs to be paid.
> e.g. a 'milestone' type progress bar that shits along like the 'Order details' text does.

In retrospect, this is a must feature. Easy to implement too. Thanks for your contribution!
