### ISSUE TITLE
Show the chat box even before the counterparty is 'online'?

### ISSUE THREAD

**Issue by dbolser** [Reckless-Satoshi/robosats#70]
**Is your feature request related to a problem? Please describe.**
As a noob, I'm not sure where the chat box should appear / if hte site may be broken / if I@m supposed to be doing something, etc.

**Describe the solution you'd like**
If the chat box appeared with teh animated text (waiting for counterparty...) I would know the state wasn't 'on me' and that I'm waiting for someone in the background.

**Describe alternatives you've considered**
* Checkign the docs to see what the chat box should look like (there is no screen shot for the web)
* Refreshing the page every 10 mins to make sure that something hasn't happened on a closed websocket or whatever.
* 

**Additional context**
Meh

**Comment by Reckless-Satoshi** [comment]
Hey @dbolser 

Thanks a lot for the input and ideas!
> **Describe the solution you'd like**
> If the chat box appeared with the animated text (waiting for counterparty...) I would know the state wasn't 'on me' and that I'm waiting for someone in the background.

This is exactly how it works, right? You just follow the `Contract box` plain text instructions and it will tell you "waiting for <bot_name> to lock escrow / submit invoice. Then you will be able to chat"

> Refreshing the page every 10 mins to make sure that something hasn't happened on a closed websocket or whatever.
Everything except the chat itself are HTTP requests that your browser is sending every X seconds. You probably won't miss it if you are looking at your browser. But there might be extra features that could be added to make sure people knows they are online and fine!

**Comment by dbolser** [comment]
Somehow the static text doesn't 'talk to me' in teh way an animation would. e.g. if the websocket dies, the animation could stop?


![2022-03-07_11-46](https://user-images.githubusercontent.com/128659/157028730-ef90bab3-9054-4ea8-aca8-e6c8b0b0712e.png)

**Comment by Reckless-Satoshi** [comment]
Got it!

**Comment by Reckless-Satoshi** [comment]
Hey @dbolser 

The new chat upgrade is very explicit about who is connected / disconnected. Two flags show on top "You: connected", "Peer: disconnected", as well as avatars will show a green or red dot over themselves. 

If the connection drops, the chat websocket will keep trying to reconnect until successful. In addition, the "Send" button will be disabled if you are not connected and will display a "Connecting..." helper text below it. The chat will however not be shown until both users have finished the step before (has to be at Fiat exchange step).

I believe this fixes any reasonable concern about whether you or your counterpart are connected. If nothing comes up will close this issue in a few days.
