### ISSUE TITLE
Error changing Pricing Method when Amount Range is enabled

### ISSUE THREAD

**Issue by zx9r** [Reckless-Satoshi/robosats#86]
When creating a new order, if Amount Range is selected under the customize tag, the behavior of the Pricing Method is not as expected. It seems that the Explicit option is desactivated, indeed if you click on Explicit the radio button is not changed (it stays as Relative) but the text box expects to enter a Explicit amount and the text below also changes according to an Explicit Pricing Method

1. Go to MAKE ORDER
2. Click on CUSTOMIZE
3. Enable Amount Range
4. Click on ORDER
5. Click on Explicit
6. Radio button is not switched but text below expects an explicit amount

**Screenshots**

![image](https://user-images.githubusercontent.com/20980128/161450465-5d4fa3d2-1d94-4b1c-be9c-c7ce87623357.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Tor Browser 
 - Version: 11.0.9 (based on Mozilla Firefox 91.7.0esr) (64-bit)

**Comment by Reckless-Satoshi** [comment]
@zx9r 
Indeed, thanks for reporting!

Once range amount is enabled, it does not make sense to use an explicit pricing method anymore. Therefore the radio button is disabled. However, it seems the disabling only applies to the appearance, yet the radio button is still clickable and works as usual...

Will simply add a fix to it on the i18n branch I am currently working on as it is a easy and minor fix.

**Comment by Reckless-Satoshi** [comment]
Solved in last merge.
