### ISSUE TITLE
Small typos on "What is RoboSats?" INFO

### ISSUE THREAD

**Issue by ibertario** [Reckless-Satoshi/robosats#88]
**1.**

There's an space and two final dots in the last phrases on this text:

![image](https://user-images.githubusercontent.com/68381662/162578264-9efe0eda-f51e-46bc-a8ec-632e77e13d7a.png)

[...] You can find a step-by-step description of the trade pipeline in [How it works](https://github.com/Reckless-Satoshi/robosats/blob/main/README.md#how-it-works)**.** You can also check the full guide in [How to use](https://github.com/Reckless-Satoshi/robosats/blob/main/docs/how-to-use.md)**.**

**2.**

The last dot must not be part of the link here:

![image](https://user-images.githubusercontent.com/68381662/162578376-093e5787-ff66-4d86-80ed-f080425382b6.png)

You can build more trust on RoboSats by [inspecting the source code](https://github.com/reckless-satoshi/robosats).

**Comment by Reckless-Satoshi** [comment]
Thanks for reporting!

Last commit fixes the issues reported in #90 , #89  and #88
