### ISSUE TITLE
Missing some icons on Desktop

### ISSUE THREAD

**Issue by ibertario** [Reckless-Satoshi/robosats#90]
**Describe the bug**

When you use RoboSats on Tor Browser Desktop, 🌍 (ANY) and 🟨 (XAU) icons are missing.

**To Reproduce**

Visit RoboSats onion site with desktop Tor Broswer.

**Screenshots**

![image](https://user-images.githubusercontent.com/68381662/162577841-0bca598d-a2f1-4ace-891f-1361b6149738.png)

![image](https://user-images.githubusercontent.com/68381662/162577847-e5f8012b-dd8c-4d5c-8f7d-c5d28deb4caa.png)

![image](https://user-images.githubusercontent.com/68381662/162577853-3043f4fe-c999-42dc-b0c1-1aa890d6488f.png)

**Browser:**

 - Tor Browser Desktop v.11.0.10

**Additional context**

The bug maybe is caused by missing fonts on the system or Tor Browser trying to block fingerprinting attacks and is blocking some unicode characters.

Using PNG images or SVG icons and avoiding unicode characters can solve this.

Also, why not use use a better XAU icon, like an small gold bar?

**Comment by Reckless-Satoshi** [comment]
> **Browser:**
> 
>     * Tor Browser Desktop v.11.0.10

As far as I know this is an issue of Mozilla (Tor Browser) on Windows. It does not support emojis. The only fix is to replace fully all emojis left for SVG icons.

**Comment by ibertario** [comment]
SVG icons definitely will look better, not a priority of course.
